# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/CharacterApi/Dockerfile'
        tags: |
          $(tag)
          latest
- stage: Publish
  displayName: Publish image
  jobs:
  - job: Publish
    displayName: Publish
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: |
          $(dockerHub)
        repository: 'hellomoon/character-api'
        command: 'push'
        tags: |
          $(tag)
          latest