apiVersion: v1
kind: Service
metadata:
  namespace: hellomoon
  name: authentication-api

spec:
  ports:
    - protocol: TCP
      name: https
      port: 443
  selector:
    app: authentication-api

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: hellomoon
  name: authentication-api
  labels:
    app: authentication-api

spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-api
  template:
    metadata:
      labels:
        app: authentication-api
    spec:
      containers:
        - name: authentication-api
          image: hellomoon/authentication-api
          ports:
            - name: https
              containerPort: 443
          env:
            - name: DatabaseUsername
              valueFrom:
                secretKeyRef:
                  name: authdb-secrets
                  key: username
            - name: DatabasePassword
              valueFrom:
                secretKeyRef:
                  name: authdb-secrets
                  key: password
            - name: ConnectionStrings__DefaultConnection
              value: "Host=authentication-db;Username=%DatabaseUsername%;Password=%DatabasePassword%;Database=authdb"
            - name: Mail__DeliveryMethod
              value: "Network"
            - name: Mail__SmtpHost
              valueFrom:
                secretKeyRef:
                  name: smtpsettings
                  key: host
            - name: Mail__SmtpPort
              valueFrom:
                secretKeyRef:
                  name: smtpsettings
                  key: port
            - name: Mail__SmtpUserName
              valueFrom:
                secretKeyRef:
                  name: smtpsettings
                  key: username
            - name: Mail__SmtpPassword
              valueFrom:
                secretKeyRef:
                  name: smtpsettings
                  key: password
            - name: ApplicationInsights__InstrumentationKey
              valueFrom:
                secretKeyRef:
                  name: applicationInsights-secrets
                  key: instrumentationKey
            - name: AuthenticationApiUrl
              value: "https://auth.hellomoon.nl"
            - name: CharacterApiUrl
              value: "https://api.hellomoon.nl/character"
            - name: GameUrl
              value: "https://game.hellomoon.nl"

---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  namespace: hellomoon
  name: authentication-api-ingressroutetls
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.hellomoon.nl`)
      kind: Rule
      services:
        - name: authentication-api
          port: 443
          scheme: https
  tls:
    certResolver: myresolver
