kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: hellomoon
  name: authentication-api-volume
  labels:
    type: local
    app: authentication-api
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/authentication-api"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: hellomoon
  name: authentication-api-volume-claim
  labels:
    app: authentication-api
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: hellomoon
  name: authentication-api

spec:
  ports:
    - protocol: TCP
      name: https
      port: 443
  selector:
    app: authentication-api

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: hellomoon
  name: authentication-api
  labels:
    app: authentication-api

spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentication-api
  template:
    metadata:
      labels:
        app: authentication-api
    spec:
      containers:
        - name: authentication-api
          image: hellomoon/authentication-api
          ports:
            - name: https
              containerPort: 443
          env:
            - name: DatabaseUsername
              valueFrom:
                secretKeyRef:
                  name: authdb-secrets
                  key: username
            - name: DatabasePassword
              valueFrom:
                secretKeyRef:
                  name: authdb-secrets
                  key: password
            - name: ConnectionStrings__DefaultConnection
              value: "Host=authentication-db;Username=%DatabaseUsername%;Password=%DatabasePassword%;Database=authdb"
            - name: Mail__DeliveryMethod
              value: "Network"
            - name: Mail__SmtpHost
              valueFrom:
                secretKeyRef:
                  name: smtpsettings
                  key: host
            - name: Mail__SmtpPort
              valueFrom:
                secretKeyRef:
                  name: smtpsettings
                  key: port
            - name: Mail__SmtpUserName
              valueFrom:
                secretKeyRef:
                  name: smtpsettings
                  key: username
            - name: Mail__SmtpPassword
              valueFrom:
                secretKeyRef:
                  name: smtpsettings
                  key: password
            - name: ApplicationInsights__InstrumentationKey
              valueFrom:
                secretKeyRef:
                  name: applicationinsights-secrets
                  key: instrumentationkey
            - name: AuthenticationApiUrl
              value: "https://auth.hellomoon.nl"
            - name: CharacterApiUrl
              value: "https://api.hellomoon.nl/character"
            - name: GameUrl
              value: "https://game.hellomoon.nl"
          volumeMounts:
            - mountPath: /app/certs
              name: certs
      volumes:
        - name: certs
          persistentVolumeClaim:
            claimName: authentication-api-volume-claim

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentication-api
  namespace: hellomoon
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - auth.hellomoon.nl
    secretName: hellomoon-auth-tls
  rules:
    - host: auth.hellomoon.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentication-api
                port:
                  number: 443
