kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: hellomoon
  name: character-db-volume
  labels:
    type: local
    app: character-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/character-db"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: hellomoon
  name: character-db-volume-claim
  labels:
    app: character-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: hellomoon
  name: character-db

spec:
  ports:
    - protocol: TCP
      name: postgresql
      port: 5432
  selector:
    app: character-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hellomoon
  name: character-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: character-db
  template:
    metadata:
      labels:
        app: character-db
    spec:
      containers:
        - name: character-db
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: characterdb-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: characterdb-secrets
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: character-db-volume-claim