apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: hellomoon
  name: character-api-stripprefix

spec:
  stripPrefix:
    prefixes:
      - /character

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: hellomoon
  name: character-api-corsheader
spec:
  headers:
    customResponseHeaders:
      Access-Control-Allow-Headers: authorization,content-type,x-grpc-web,x-user-agent
      Access-Control-Allow-Methods: "*"
      Access-Control-Allow-Origin: "*"
      Access-Control-Expose-Headers: Grpc-Status,Grpc-Message,Grpc-Encoding,Grpc-Accept-Encoding

---
apiVersion: v1
kind: Service
metadata:
  namespace: hellomoon
  name: character-api

spec:
  ports:
    - protocol: TCP
      name: https
      port: 443
  selector:
    app: character-api

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: hellomoon
  name: character-api
  labels:
    app: character-api

spec:
  replicas: 1
  selector:
    matchLabels:
      app: character-api
  template:
    metadata:
      labels:
        app: character-api
    spec:
      containers:
        - name: character-api
          image: hellomoon/character-api
          ports:
            - name: https
              containerPort: 443
          env:
            - name: DatabaseUsername
              valueFrom:
                secretKeyRef:
                  name: characterdb-secrets
                  key: username
            - name: DatabasePassword
              valueFrom:
                secretKeyRef:
                  name: characterdb-secrets
                  key: password
            - name: ConnectionStrings__DefaultConnection
              value: "Host=character-db;Username=%DatabaseUsername%;Password=%DatabasePassword%;Database=characterdb"
            - name: ApplicationInsights__InstrumentationKey
              valueFrom:
                secretKeyRef:
                  name: applicationinsights-secrets
                  key: instrumentationkey
            - name: AuthenticationApiUrl
              value: "https://auth.hellomoon.nl"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: character-api
  namespace: hellomoon
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: "hellomoon-character-api-stripprefix@kubernetescrd,hellomoon-character-api-corsheader@kubernetescrd"
spec:
  tls:
  - hosts:
    - api.hellomoon.nl
    secretName: hellomoon-api-tls
  rules:
    - host: api.hellomoon.nl
      http:
        paths:
          - path: /character
            pathType: Prefix
            backend:
              service:
                name: character-api
                port:
                  number: 443
