version: "3.9"

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: this_is_a_public_password

  authentication-api:
    build: 
      dockerfile: ../src/Services/Authentication/Authentication.API/Dockerfile
      context: ../src
    restart: always
    ports:
      - 5000:443
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Username=postgres;Password=this_is_a_public_password;Database=authdb
      GameUrl: http://localhost:3000

  adminer:
    image: adminer
    restart: always
    ports:
      - 3100:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce

  character-api:
    build: 
      dockerfile: ../src/Services/Character/Character.API/Dockerfile
      context: ../src
    restart: always
    ports:
      - 5001:443
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Username=postgres;Password=this_is_a_public_password;Database=charactersdb
      AuthenticationApiUrl: https://authentication-api:443
      Logging__LogLevel__Microsoft: Debug
    labels:
