version: "3.9"

services:

  authentication-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: this_is_a_public_password

  authentication-api:
    build: ../src/AuthenticationApi
    restart: always
    ports:
      - 5000:443
    environment:
      ConnectionStrings__DefaultConnection: Host=authentication-db;Username=postgres;Password=this_is_a_public_password;Database=authdb
      GameUrl: http://localhost:3000

  adminer:
    image: adminer
    restart: always
    ports:
      - 3100:8080
    environment:
      ADMINER_DEFAULT_SERVER: authentication-db
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce

  character-api:
    build: ../src/CharacterApi
    restart: always
    ports:
      - 5001:443