apiVersion: v1
kind: Secret
metadata:
  namespace: hellomoon
  name: smtpsettings
type: Opaque
data:
  host:
  port:
  username:
  password:

---
apiVersion: v1
kind: Secret
metadata:
  namespace: hellomoon
  name: characterdb-secrets
type: Opaque
data:
  username:
  password:

---
apiVersion: v1
kind: Secret
metadata:
  namespace: hellomoon
  name: authdb-secrets
type: Opaque
data:
  username:
  password:

---
apiVersion: v1
kind: Secret
metadata:
  namespace: hellomoon
  name: applicationinsights-secrets
type: Opaque
data:
  instrumentationkey:
