apiVersion: v1
kind: Secret
metadata:
  namespace: hellomoon
  name: smtpsettings
type: Opaque
data:
  host:
  port:
  username: 
  password:

---
apiVersion: v1
kind: Secret
metadata:
  namespace: hellomoon
  name: characterdb-secrets
type: Opaque
data:
  username: 
  password: 