kind: Namespace
apiVersion: v1
metadata:
  name: hellomoon
  labels:
    name: hellomoon
---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: hellomoon
  name: build-robot
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: hellomoon
  name: azure-devops-deploy-role
rules:
- apiGroups: ["", "extensions", "apps", "traefik.containo.us", "rbac.authorization.k8s.io", "apiextensions.k8s.io"]
  resources: ["namespaces", "deployments", "replicasets", "pods", "services", "middlewares", "ingressroutes", "configmaps", "serviceaccounts", "roles", "rolebindings", "clusterroles", "clusterrolebindings", "customresourcedefinitions", "persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: azure-devops-deploy-manager
  namespace: hellomoon
subjects:
- kind: ServiceAccount
  name: build-robot
  namespace: hellomoon
roleRef:
  kind: ClusterRole
  name: azure-devops-deploy-role
  apiGroup: rbac.authorization.k8s.io