kind: Namespace
apiVersion: v1
metadata:
  name: hellomoon
  labels:
    name: hellomoon
---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: hellomoon
  name: build-robot
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: hellomoon
  name: build-robot-admin
subjects:
  - kind: ServiceAccount
    name: build-robot
    namespace: hellomoon
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io