kind: Namespace
apiVersion: v1
metadata:
  name: hellomoon
  labels:
    name: hellomoon
---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: hellomoon
  name: build-robot
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: hellomoon
  name: azure-devops-deploy-role
rules:
- apiGroups: ["", "extensions", "apps", "traefik.containo.us"]
  resources: ["namespaces", "deployments", "replicasets", "pods", "services", "middlewares", "ingressroutes", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: azure-devops-deploy-manager
  namespace: hellomoon
subjects:
- kind: ServiceAccount
  name: build-robot
  namespace: hellomoon
roleRef:
  kind: Role
  name: azure-devops-deploy-role
  apiGroup: rbac.authorization.k8s.io